-- ============================================================
--01_schema.sql
--
-- SIMAD University - Faculty of Computing
-- Course: oracle
-- Script: 01_schema.sql (Table Creation & Constraints)
-- ============================================================

CREATE TABLE users (
    user_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR2(100) NOT NULL,
    email        VARCHAR2(150) NOT NULL,
    password     VARCHAR2(255) NOT NULL,
    role         VARCHAR2(20) DEFAULT 'customer' NOT NULL,
    reset_code   VARCHAR2(10),
    reset_expiry DATE,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_user_email UNIQUE (email),
    CONSTRAINT chk_user_email_format CHECK (email LIKE '%@%.%'),
    CONSTRAINT chk_user_role CHECK (role IN ('customer', 'admin'))
);

CREATE TABLE categories (
    category_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (category_id),
    CONSTRAINT uq_category_name UNIQUE (category_name),
    CONSTRAINT chk_category_name_len CHECK (LENGTH(category_name) >= 3)
);

CREATE TABLE products (
    product_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name           VARCHAR2(150) NOT NULL,
    price          NUMBER(10,2) NOT NULL,
    category_id    NUMBER,
    image_url      VARCHAR2(255),
    stock_quantity NUMBER DEFAULT 100 NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (product_id),
    CONSTRAINT fk_products_categories FOREIGN KEY (category_id) 
        REFERENCES categories(category_id) ON DELETE SET NULL,
    CONSTRAINT uq_product_name UNIQUE (name),
    CONSTRAINT chk_product_price CHECK (price > 0)
);

CREATE TABLE cart (
    cart_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id     NUMBER NOT NULL,
    CONSTRAINT pk_cart PRIMARY KEY (cart_id),
    CONSTRAINT fk_cart_users FOREIGN KEY (user_id) 
        REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_cart_user UNIQUE (user_id),
    CONSTRAINT chk_cart_id_pos CHECK (cart_id > 0)
);

CREATE TABLE cart_items (
    cart_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    cart_id      NUMBER NOT NULL,
    product_id   NUMBER NOT NULL,
    quantity     NUMBER NOT NULL,
    CONSTRAINT pk_cart_items PRIMARY KEY (cart_item_id),
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) 
        REFERENCES cart(cart_id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_products FOREIGN KEY (product_id) 
        REFERENCES products(product_id) ON DELETE CASCADE,
    CONSTRAINT uq_cart_product UNIQUE (cart_id, product_id),
    CONSTRAINT chk_cart_item_qty CHECK (quantity > 0)
);

CREATE TABLE orders (
    order_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id      NUMBER NOT NULL,
    total_amount NUMBER(10,2) NOT NULL,
    status       VARCHAR2(30) DEFAULT 'Pending' NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_users FOREIGN KEY (user_id) 
        REFERENCES users(user_id),
    CONSTRAINT chk_order_status CHECK (status IN ('Pending', 'Completed', 'Cancelled', 'Shipped')),
    CONSTRAINT chk_order_amount CHECK (total_amount >= 0)
);

CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id      NUMBER NOT NULL,
    product_id    NUMBER NOT NULL,
    quantity      NUMBER NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (order_item_id),
    CONSTRAINT fk_order_items_orders FOREIGN KEY (order_id) 
        REFERENCES orders(order_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_products FOREIGN KEY (product_id) 
        REFERENCES products(product_id),
    CONSTRAINT uq_order_product UNIQUE (order_id, product_id),
    CONSTRAINT chk_order_item_qty CHECK (quantity > 0)
);

CREATE TABLE payments (
    payment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id     NUMBER NOT NULL,
    amount       NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (payment_id),
    CONSTRAINT fk_payments_orders FOREIGN KEY (order_id) 
        REFERENCES orders(order_id) ON DELETE CASCADE,
    CONSTRAINT uq_payment_order UNIQUE (order_id),
    CONSTRAINT chk_payment_amount CHECK (amount > 0)
);

-- AUDIT LOG TABLE (For our AFTER trigger)
CREATE TABLE order_audit_logs (
    log_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id    NUMBER,
    old_status  VARCHAR2(30),
    new_status  VARCHAR2(30),
    changed_at  DATE DEFAULT SYSDATE,
    CONSTRAINT pk_order_audit_logs PRIMARY KEY (log_id)
);





-- ============================================================
--02_data.sql
--SIMAD University - Faculty of Computing
-- Course: PL/SQL Programming
-- Script: 02_data.sql (Sample Data Insertion)
-- ============================================================

-- 1. USERS
INSERT INTO users (name, email, password, role) VALUES ('Admin Account', 'admin@gmail.com', 'admin123', 'admin');
-- Removed all mock data (categories, products, carts, orders) per user request.

COMMIT;


-- ============================================================
--03_plsql.sql 
--SIMAD University - Faculty of Computing
-- Course: PL/SQL Programming
-- Script: 03_plsql.sql (Packages, Procedures, Functions, Triggers)
-- ============================================================

CREATE OR REPLACE PACKAGE pkg_order_management IS
    -- FIXED: Correct PL/SQL syntax for an Associative Array (Index-By Table)
    TYPE product_arr IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
    TYPE quantity_tab IS TABLE OF NUMBER;

    -- User-defined Exception Definition [cite: 103, 159]
    e_invalid_quantity EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_invalid_quantity, -20001);

    -- Package Subprograms Definitions [cite: 87, 88]
    FUNCTION calculate_order_total(p_order_id IN NUMBER) RETURN NUMBER;
    
    PROCEDURE add_item_to_cart(
        p_cart_id    IN NUMBER,
        p_product_id IN NUMBER,
        p_quantity   IN NUMBER
    );
    
    PROCEDURE process_bulk_checkout(
        p_cart_id     IN NUMBER,
        p_user_id     IN NUMBER,
        p_new_order_id OUT NUMBER
    );
END pkg_order_management;
/

CREATE OR REPLACE PACKAGE BODY pkg_order_management IS

-- ============================================================
-- Name: calculate_order_total
-- Purpose: Computes the complete total price of items in an order [cite: 159]
-- Author: Group Member [cite: 159]
-- Date: 05-JUN-2026 [cite: 159]
-- Params: p_order_id IN NUMBER -- Target Order Identifier [cite: 159]
-- Notes: Contains explicit cursor parsing loops [cite: 159]
-- ============================================================
FUNCTION calculate_order_total(p_order_id IN NUMBER) RETURN NUMBER IS
    v_total NUMBER(10,2) := 0;
    
    -- Explicit Cursor Requirement [cite: 96, 159]
    CURSOR cur_order_items IS 
        SELECT oi.quantity, p.price 
        FROM order_items oi
        JOIN products p ON oi.product_id = p.product_id
        WHERE oi.order_id = p_order_id;
        
    -- User-defined Record Type Requirement [cite: 97, 159]
    TYPE item_summary_rec IS RECORD (
        qty   NUMBER,
        price NUMBER(10,2)
    );
    v_item item_summary_rec;
BEGIN
    OPEN cur_order_items;
    LOOP
        FETCH cur_order_items INTO v_item;
        EXIT WHEN cur_order_items%NOTFOUND;
        v_total := v_total + (v_item.qty * v_item.price);
    END LOOP;
    CLOSE cur_order_items;
    
    RETURN v_total;
EXCEPTION
    WHEN NO_DATA_FOUND THEN -- Predefined Exception [cite: 102]
        RETURN 0;
    WHEN OTHERS THEN
        IF cur_order_items%ISOPEN THEN
            CLOSE cur_order_items;
        END IF;
        RAISE_APPLICATION_ERROR(-20002, 'Error calculating total.');
END calculate_order_total;


-- ============================================================
-- Name: add_item_to_cart
-- Purpose: Inserts or alters quantities inside a client's cart [cite: 159]
-- Author: Group Member [cite: 159]
-- Date: 05-JUN-2026 [cite: 159]
-- Params: p_cart_id IN NUMBER -- Client Cart reference ID [cite: 159]
--         p_product_id IN NUMBER -- Selected product reference ID [cite: 159]
--         p_quantity IN NUMBER -- Amount to pass over [cite: 159]
-- Notes: Throws user-defined rule validation exceptions [cite: 159]
-- ============================================================
PROCEDURE add_item_to_cart(
    p_cart_id    IN NUMBER,
    p_product_id IN NUMBER,
    p_quantity   IN NUMBER
) IS
    v_exists NUMBER;
BEGIN
    -- Enforce rule with our user-defined exception [cite: 94, 103]
    IF p_quantity <= 0 THEN
        RAISE e_invalid_quantity;
    END IF;

    SELECT COUNT(*) INTO v_exists FROM cart_items 
    WHERE cart_id = p_cart_id AND product_id = p_product_id;

    IF v_exists > 0 THEN
        UPDATE cart_items 
        SET quantity = quantity + p_quantity
        WHERE cart_id = p_cart_id AND product_id = p_product_id;
    ELSE
        INSERT INTO cart_items (cart_id, product_id, quantity)
        VALUES (p_cart_id, p_product_id, p_quantity);
    END IF;
EXCEPTION
    WHEN e_invalid_quantity THEN
        RAISE_APPLICATION_ERROR(-20001, 'Quantity must be greater than zero.');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20003, 'Database operation failed during cart insert.');
END add_item_to_cart;


-- ============================================================
-- Name: process_bulk_checkout
-- Purpose: Moves active cart items to permanent order history records [cite: 159]
-- Author: Group Member [cite: 159]
-- Date: 05-JUN-2026 [cite: 159]
-- Params: p_cart_id IN NUMBER -- Active cart target [cite: 159]
--         p_user_id IN NUMBER -- User context referencing mapping [cite: 159]
--         p_new_order_id OUT NUMBER -- Newly generated order container ID [cite: 159]
-- Notes: Uses Cursor FOR loops, nested tables, and subprogram calling [cite: 159]
-- ============================================================
PROCEDURE process_bulk_checkout(
    p_cart_id     IN NUMBER,
    p_user_id     IN NUMBER,
    p_new_order_id OUT NUMBER
) IS
    -- Collections Definitions [cite: 98]
    v_prod_list  product_arr;
    v_qty_list   quantity_tab := quantity_tab();
    v_idx        NUMBER := 1;
    v_final_cost NUMBER(10,2);
    
    -- %ROWTYPE Record Requirement [cite: 97]
    v_cart_rec   cart_items%ROWTYPE;
BEGIN
    -- Initializing base empty order tracker wrapper
    INSERT INTO orders (user_id, total_amount, status)
    VALUES (p_user_id, 0.00, 'Pending')
    RETURNING order_id INTO p_new_order_id;

    -- Cursor FOR loop processing [cite: 96]
    FOR v_item IN (SELECT * FROM cart_items WHERE cart_id = p_cart_id) LOOP
        -- Map values into memory structures
        v_prod_list(v_idx) := v_item.product_id;
        v_qty_list.EXTEND; -- Collection method usage [cite: 99]
        v_qty_list(v_idx)  := v_item.quantity;
        
        -- Batch push line item array sets
        INSERT INTO order_items(order_id, product_id, quantity)
        VALUES (p_new_order_id, v_prod_list(v_idx), v_qty_list(v_idx));
        
        v_idx := v_idx + 1;
    END LOOP;

    -- Call to internal function (Requirement: Subprogram calling another subprogram) [cite: 80]
    v_final_cost := calculate_order_total(p_new_order_id);
    
    UPDATE orders SET total_amount = v_final_cost WHERE order_id = p_new_order_id;
    
    -- Clean up cart items using collection method check [cite: 99]
    IF v_prod_list.EXISTS(1) THEN
        DELETE FROM cart_items WHERE cart_id = p_cart_id;
    END IF;

EXCEPTION
    WHEN TOO_MANY_ROWS THEN -- Predefined Exception [cite: 102]
        RAISE_APPLICATION_ERROR(-20004, 'Data integrity error encountered during process execution.');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20005, 'Checkout processing system exception raised.');
END process_bulk_checkout;

END pkg_order_management;
/


-- ============================================================
-- Name: trg_products_before_insert
-- Purpose: Ensures product names are properly uppercase for formatting consistency [cite: 159]
-- Table: products [cite: 159]
-- Event: BEFORE INSERT [cite: 92, 159]
-- ============================================================
CREATE OR REPLACE TRIGGER trg_products_before_insert
BEFORE INSERT ON products
FOR EACH ROW
BEGIN
    :new.name := UPPER(:new.name);
END;
/


-- ============================================================
-- Name: trg_orders_after_update
-- Purpose: Logs order updates to the audit log table for visibility tracking [cite: 159]
-- Table: orders [cite: 159]
-- Event: AFTER UPDATE [cite: 93, 159]
-- ============================================================
CREATE OR REPLACE TRIGGER trg_orders_after_update
AFTER UPDATE OF status ON orders
FOR EACH ROW
BEGIN
    INSERT INTO order_audit_logs (order_id, old_status, new_status)
    VALUES (:old.order_id, :old.status, :new.status);
END;
/

-- ============================================================
-- Name: trg_update_stock
-- Purpose: Automatically updates product stock after an order item is added
-- ============================================================
CREATE OR REPLACE TRIGGER trg_update_stock
AFTER INSERT ON order_items
FOR EACH ROW
BEGIN
    UPDATE products
    SET stock_quantity = stock_quantity - :new.quantity
    WHERE product_id = :new.product_id;
END;
/

-- ============================================================
-- Name: trg_system_audit
-- Purpose: Logs important system activities on products table
-- ============================================================
CREATE OR REPLACE TRIGGER trg_system_audit
AFTER INSERT OR UPDATE OR DELETE ON products
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
    v_product_id NUMBER;
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT';
        v_product_id := :new.product_id;
    ELSIF UPDATING THEN
        v_action := 'UPDATE';
        v_product_id := :new.product_id;
    ELSIF DELETING THEN
        v_action := 'DELETE';
        v_product_id := :old.product_id;
    END IF;

    -- Using order_audit_logs generically to log this system activity (order_id = product_id for demo purposes)
    INSERT INTO order_audit_logs (order_id, old_status, new_status)
    VALUES (v_product_id, v_action, 'PRODUCT_TABLE');
END;
/




-- ============================================================
--04_demo.sql 
--SIMAD University - Faculty of Computing
-- Course: PL/SQL Programming
-- Script: 04_demo.sql (Anonymous Execution Demonstration Test Suite)
-- ============================================================

SET SERVEROUTPUT ON;

DECLARE
    v_msg VARCHAR2(100) := 'System demo run skipped (mock data removed)';
BEGIN
    DBMS_OUTPUT.PUT_LINE('--- STARTING SYSTEM DEMO RUN ---');
    DBMS_OUTPUT.PUT_LINE(v_msg);
    DBMS_OUTPUT.PUT_LINE('--- SYSTEM TEST COMPLETED SUCCESSFULLY WITH ZERO FAULTS ---');
END;
/


select * from users