-- ============================================================
-- SIMAD University - Faculty of Computing
-- Course: Oracle Database & PL/SQL Programming
-- Script: 01_schema.sql (Table Creation & Constraints)
-- ============================================================

CREATE TABLE users (
    user_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR2(100) NOT NULL,
    email        VARCHAR2(150) NOT NULL,
    password     VARCHAR2(255) NOT NULL,
    role         VARCHAR2(20) DEFAULT 'customer' NOT NULL,
    reset_code   VARCHAR2(10),
    reset_expiry DATE,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_user_email UNIQUE (email),
    CONSTRAINT chk_user_email_format CHECK (email LIKE '%@%.%'),
    CONSTRAINT chk_user_role CHECK (role IN ('customer', 'admin'))
);

CREATE TABLE categories (
    category_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (category_id),
    CONSTRAINT uq_category_name UNIQUE (category_name),
    CONSTRAINT chk_category_name_len CHECK (LENGTH(category_name) >= 3)
);

CREATE TABLE products (
    product_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name           VARCHAR2(150) NOT NULL,
    price          NUMBER(10,2) NOT NULL,
    category_id    NUMBER,
    image_url      VARCHAR2(255),
    stock_quantity NUMBER DEFAULT 100 NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (product_id),
    CONSTRAINT fk_products_categories FOREIGN KEY (category_id) 
        REFERENCES categories(category_id) ON DELETE SET NULL,
    CONSTRAINT uq_product_name UNIQUE (name),
    CONSTRAINT chk_product_price CHECK (price > 0)
);

CREATE TABLE cart (
    cart_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id     NUMBER NOT NULL,
    CONSTRAINT pk_cart PRIMARY KEY (cart_id),
    CONSTRAINT fk_cart_users FOREIGN KEY (user_id) 
        REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_cart_user UNIQUE (user_id),
    CONSTRAINT chk_cart_id_pos CHECK (cart_id > 0)
);

CREATE TABLE cart_items (
    cart_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    cart_id      NUMBER NOT NULL,
    product_id   NUMBER NOT NULL,
    quantity     NUMBER NOT NULL,
    CONSTRAINT pk_cart_items PRIMARY KEY (cart_item_id),
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) 
        REFERENCES cart(cart_id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_products FOREIGN KEY (product_id) 
        REFERENCES products(product_id) ON DELETE CASCADE,
    CONSTRAINT uq_cart_product UNIQUE (cart_id, product_id),
    CONSTRAINT chk_cart_item_qty CHECK (quantity > 0)
);

CREATE TABLE orders (
    order_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id      NUMBER NOT NULL,
    total_amount NUMBER(10,2) NOT NULL,
    status       VARCHAR2(30) DEFAULT 'Pending' NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_users FOREIGN KEY (user_id) 
        REFERENCES users(user_id),
    CONSTRAINT chk_order_status CHECK (status IN ('Pending', 'Completed', 'Cancelled', 'Shipped')),
    CONSTRAINT chk_order_amount CHECK (total_amount >= 0)
);

CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id      NUMBER NOT NULL,
    product_id    NUMBER NOT NULL,
    quantity      NUMBER NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (order_item_id),
    CONSTRAINT fk_order_items_orders FOREIGN KEY (order_id) 
        REFERENCES orders(order_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_products FOREIGN KEY (product_id) 
        REFERENCES products(product_id),
    CONSTRAINT uq_order_product UNIQUE (order_id, product_id),
    CONSTRAINT chk_order_item_qty CHECK (quantity > 0)
);

CREATE TABLE payments (
    payment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id     NUMBER NOT NULL,
    amount       NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (payment_id),
    CONSTRAINT fk_payments_orders FOREIGN KEY (order_id) 
        REFERENCES orders(order_id) ON DELETE CASCADE,
    CONSTRAINT uq_payment_order UNIQUE (order_id),
    CONSTRAINT chk_payment_amount CHECK (amount > 0)
);

-- AUDIT LOG TABLE
CREATE TABLE order_audit_logs (
    log_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id    NUMBER,
    old_status  VARCHAR2(30),
    new_status  VARCHAR2(30),
    changed_at  DATE DEFAULT SYSDATE,
    CONSTRAINT pk_order_audit_logs PRIMARY KEY (log_id)
);
